### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.six'

### ISSUE THREAD

**Issue by urmeya** [allenai/scidocs#11]
I have followed exact following steps given in README section to create the environment for SciDocs:

```
git clone https://github.com/allenai/scidocs.git
cd scidocs
conda create -y --name scidocs python==3.7
conda activate scidocs
conda install -y -q -c conda-forge numpy pandas scikit-learn jsonlines tqdm sklearn-contrib-lightning pytorch
pip install pytrec_eval awscli allennlp==0.9
python setup.py install

aws s3 sync --no-sign-request s3://ai2-s2-research-public/specter/scidocs/ data/
```
Using following command given in the README section, I tried to evaluate the original SPECTER embeddings provided in the data.

`python scripts/run.py --cls data/specter-embeddings/cls.jsonl --user-citation data/specter-embeddings/user-citation.jsonl --recomm data specter-embeddings/recomm.jsonl --val_or_test test --n-jobs 12 --cuda-device -1`

I am getting following error:

```
Traceback (most recent call last):
  File "scripts/run.py", line 2, in <module>
    from scidocs.paths import DataPaths
  File "/opt/conda/envs/scidocs/lib/python3.7/site-packages/scidocs-0.0.1-py3.7.egg/scidocs/__init__.py", line 1, in <module>
    from scidocs.classification import get_mag_mesh_metrics
  File "/opt/conda/envs/scidocs/lib/python3.7/site-packages/scidocs-0.0.1-py3.7.egg/scidocs/classification.py", line 7, in <module>
    from lightning.classification import LinearSVC
  File "/opt/conda/envs/scidocs/lib/python3.7/site-packages/lightning/classification.py", line 1, in <module>
    from .impl.adagrad import AdaGradClassifier
  File "/opt/conda/envs/scidocs/lib/python3.7/site-packages/lightning/impl/adagrad.py", line 8, in <module>
    from sklearn.externals.six.moves import xrange
ModuleNotFoundError: No module named 'sklearn.externals.six'
```
Please help me in solving this issue. Output of `conda list` is pasted below.

```
# packages in environment at /opt/conda/envs/scidocs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
alabaster                 0.7.12                   pypi_0    pypi
allennlp                  0.9.0                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
awscli                    1.18.61                  pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
blas                      1.0                         mkl  
blis                      0.2.4                    pypi_0    pypi
boto3                     1.13.11                  pypi_0    pypi
botocore                  1.16.11                  pypi_0    pypi
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
conllu                    1.3.1                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.3                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
editdistance              0.5.3                    pypi_0    pypi
flaky                     3.6.1                    pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
flask-cors                3.0.8                    pypi_0    pypi
ftfy                      5.7                      pypi_0    pypi
gevent                    20.5.0                   pypi_0    pypi
greenlet                  0.4.15                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.9                      pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        1.6.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    0.15.0                     py_0    conda-forge
jsonlines                 1.2.0                      py_1    conda-forge
jsonnet                   0.15.0                   pypi_0    pypi
jsonpickle                1.4.1                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
more-itertools            8.3.0                    pypi_0    pypi
murmurhash                1.0.2                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.0               hc9558a2_0    conda-forge
nltk                      3.5                      pypi_0    pypi
numpy                     1.18.4           py37h8960a57_0    conda-forge
numpydoc                  0.9.2                    pypi_0    pypi
openssl                   1.0.2u               h516909a_0    conda-forge
overrides                 3.0.0                    pypi_0    pypi
packaging                 20.3                     pypi_0    pypi
pandas                    1.0.3            py37h0da4684_1    conda-forge
parsimonious              0.8.1                    pypi_0    pypi
pip                       20.0.2                   py37_3  
plac                      0.9.6                    pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
preshed                   2.0.1                    pypi_0    pypi
protobuf                  3.12.0                   pypi_0    pypi
py                        1.8.1                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    5.4.2                    pypi_0    pypi
python                    3.7.0                h6e4f718_3  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           cuda101py37h02f0884_0  
pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
pytorch-transformers      1.1.0                    pypi_0    pypi
pytrec-eval               0.4                      pypi_0    pypi
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
regex                     2020.5.14                pypi_0    pypi
requests                  2.23.0                   pypi_0    pypi
responses                 0.10.14                  pypi_0    pypi
rsa                       3.4.2                    pypi_0    pypi
s3transfer                0.3.3                    pypi_0    pypi
scidocs                   0.0.1                    pypi_0    pypi
scikit-learn              0.23.0           py37h8a51577_0    conda-forge
scipy                     1.4.1            py37ha3d9a3c_3    conda-forge
sentencepiece             0.1.90                   pypi_0    pypi
setuptools                46.2.0                   py37_0  
six                       1.14.0                     py_1    conda-forge
sklearn-contrib-lightning 0.5.0            py37hb3f55d8_1    conda-forge
snowballstemmer           2.0.0                    pypi_0    pypi
spacy                     2.1.9                    pypi_0    pypi
sphinx                    3.0.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.31.1               h62c20be_1  
sqlparse                  0.3.1                    pypi_0    pypi
srsly                     1.0.2                    pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
thinc                     7.0.8                    pypi_0    pypi
threadpoolctl             2.0.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.8                hbc83047_0  
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
unidecode                 1.1.1                    pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
wasabi                    0.6.0                    pypi_0    pypi
wcwidth                   0.1.9                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0  
word2number               1.1                      pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
```

**Comment by sergeyf** [comment]
Thanks for the bug report. Looks like the latest version of `sklearn` doesn't have support for Python 2.x, but the `lightning` package still expects it. I'll fix later today and will report back.

**Comment by sergeyf** [comment]
@urmeya I believe this can be fixed easily by pinning the sklearn version. Will you please try the following?

`conda install -y -q -c conda-forge scikit-learn=0.22.2`

And then rerun?

**Comment by urmeya** [comment]
Thanks @sergeyf This solution worked.
